[meta]
schedule = https://data.c3voc.de/kde2026/schedule.xml
schedule_format=xml
;; path to background video
template = intro_v2.mp4
;; whether background video uses transparency (needs to be .mov)
alpha = false
;; whether background video is prores 4444
prores = false
;; in and out time format: t for seconds, n for frame number
inout_type = t
;; fade-in duration (seconds), leave out or set to zero to disable
fade_duration = 1.0

;; Some font settings can have defaults, which can be overridden in the
;; 'title', 'speaker' and 'text' sections below.
[default]
;; default font
fontfile = BrutalMilkNo2-Medium.ttf
;; default font color
fontcolor = #102832

;; fields for title and speaker names are empty in the template.ts, so we'll render them in via ffmpeg
;; parameters are:
;; - in:          start frame/ time
;; - out:         end frame/ time
;; - fontfile:    font file
;; - fontcolor:   font color
;; - fontsize:    font size (pixel)
;; - x:           horizontal position (top left corner)
;; - y:           vertical position (top left corner)
[title]
in = 5.0
out = 8.6
fontsize = 100
x = 0
y = 480
alignment = center

[speaker]
in = 5.0
out = 8.6
fontsize = 65
x = 0
y = 590
alignment = center
fontfile = BrutalMilkNo2-Light.ttf

;; optional extra text, comment out "text" field to disable
[text]
in = 0
out = 0
fontsize = 0
x = 0
y = 0
;text = some additional text
