[meta]
schedule = https://www.emfcamp.org/schedule/2026.frab.xml?venue_ids=75,76,77,113,129
schedule_format = xml
template = intro.ts
alpha = false
prores = false
inout_type = t
fade_duration = 0.5

[default]
fontfile = Raleway-NotoEmoji-2024.ttf
fontcolor = #FFFFFF

;; fields for title and speaker names are empty in the template.ts, so we'll render them in via ffmpeg
;; parameters are:
;; - in:          start frame/ time
;; - out:         end frame/ time
;; - fontfile:    font file
;; - fontcolor:   font color
;; - fontsize:    font size (pixel)
;; - x:           horizontal position (top left corner)
;; - y:           vertical position (top left corner)
[title]
in = 7.5
out = 12.5
fontsize = 80
x = 600
y = 600

[speaker]
in = 7.5
out = 12.5
fontsize = 50
x = 600
y = 500
fontcolor = #F77F02

;; optional extra text, comment out "text" field to disable
[text]
in = 1
out = 10
fontsize = 70
x = 50
y = 678
text = 
