[meta]
schedule = https://pretalx.c3voc.de/jhhh23/schedule/export/schedule.xml
template = intro-background.ts
alpha = false
prores = false
inout_type = t
fade_duration = 0.5

[default]
fontfile = GeistMono-Bold.ttf
fontcolor = #000000

;; fields for title and speaker names are empty in the template.ts, so we'll render them in via ffmpeg
;; parameters are:
;; - in:          start frame/ time
;; - out:         end frame/ time
;; - fontfile:    font file
;; - fontcolor:   font color
;; - fontsize:    font size (pixel)
;; - x:           horizontal position (top left corner)
;; - y:           vertical position (top left corner)
[title]
# 785-940px
in = 1
out = 9.5
fontsize = 80
x = 50
y = 840

[speaker]
# 940-1080px
in = 2
out = 9
fontsize = 50
x = 50
y = 970
fontfile = GeistMono-Regular.ttf

;; optional extra text, comment out "tdxt" field to disable
[text]
# 630 - 785px
in = 1
out = 10
fontsize = 70
x = 50
y = 678
text = Berlin 2026
